### ISSUE TITLE
OS-X: VSTs not found

### ISSUE THREAD

**Issue by nodepond** [logsol/Pd-Pulp#6]
I put "Pd Pulp.vst" and "PD Pulp FX.vst" in the System VST folder and also tried it in the custom VST-folder. Both does not work. I just can't see the VST from in inside Ableton Live (9 Suite btw).

Are there any dependencies I've overseen? 

If I doubleclick one file I get the error: "Error #-5000 while verifying your authorisation. Unknown Error." with the maxMSP-logo besides it.

**Comment by logsol** [comment]
Are you running Live in 32 or 64 bit mode?

**Comment by nodepond** [comment]
It's 64-bit.

**Comment by nodepond** [comment]
...downloading the 32-bit version. Will try it with that..

**Comment by nodepond** [comment]
This worked! Would be nice to have a short notice about the 32-bit mode in the Readme. Thanks!
