### ISSUE TITLE
loading externals ability?

### ISSUE THREAD

**Issue by MartinHN** [logsol/Pd-Pulp#7]
I can't find a way to load pd_darwin externals.
I didn't managed to make it work out of the box : 
when loading a patch it complains about symbol not founds
- Ex : coll.pd_darwin (in the same path than loaded pd patch) gives :
  rec : /Users/mhermant/Documents/Work/Dev/PD/hierarchicalShift/coll.pd_darwin: dlopen(/Users/mhermant/Documents/Work/Dev/PD/hierarchicalShift/coll.pd_darwin, 10): Symbol not found: _s_float
  Referenced from: /Users/mhermant/Documents/Work/Dev/PD/hierarchicalShift/coll.pd_darwin
  Expected in: /Users/mhermant/Documents/Work/Dev/JUCE/examples/audio plugin host/Builds/MacOSX/build/Debug/Plugin Host.app/Contents/MacOS/Plugin Host

I know that libpd apps have the ability to load externals but it seems harder if it's from a bundle

Do you know anything about it?

I've tried : 
-  different combinations of linker flags like -flat_namespace / -bundle_loader / -undefined dynamic_lookup without success 
- compiling libpd with these flags also

PS : I debug VSTs via Juce's Plugin Host

Thanks for this great project!

**Comment by o-g-sus** [comment]
Don't know if there is your solution written, but do you know that document? https://www.safaribooksonline.com/library/view/making-musical-apps/9781449331375/ch04.html

So in general it is possible to use externals with libPD, but I have not used them so far

**Comment by MartinHN** [comment]
late answer, but it appeared that only cyclone objects can't load dynamically
Other seems to be fine
this bug is reproducible taking  compiled .pd_darwin from extended
and running patch from pd-Vanilla

my workaround, is to compile it in pd pulp itself...
if any one has an other, it will be more than welcome

Cheers

**Comment by logsol** [comment]
Thanks for sharing!
