### ISSUE TITLE
Porting to WDL-OL

### ISSUE THREAD

**Issue by mavavilj** [logsol/Pd-Pulp#9]
I'm thinking of doing a fork to port this to WDL-OL, because I'm finding JUCE a bit too complex for this and WDL-OL more simple as well as MIT-licensed.

Can you clarify what parts of the code are independent of JUCE, so that I could extract those for the WDL-OL port?

**Comment by logsol** [comment]
In this project you could say that JUCE starts where libpd ends. It's pretty dependent upon JUCE but its not very much code so it should be easily possible for you to just reimplement everything using WDL-OL and some UI library.
